### ISSUE TITLE
Set privilege

### ISSUE THREAD

**Issue by gorbushka** [carlmontanari/nornir_scrapli#1]
Hello. I try to use nornir_scrapli with exec privilege and when i try to set default_desired_privilege_level = exec there is an error

`TypeError: __init__() got multiple values for keyword argument 'default_desired_privilege_level'`

Am i doing something wrong or it's just bug?
This config with default example
```
---
iosxe-1:
  hostname: 172.17.9.125
  username: admin
  password: admin
  connection_options:
    scrapli:
      platform: cisco_iosxe
      port: 22
      extras:
        default_desired_privilege_level: "exec"
        ssh_config_file: True
        auth_strict_key: False

```

Or could you explain how to use generic driver with on_open scrapli key-function in nornir_scrapli?
